---
Neos:
  MarketPlace:
    typeMapping:
      'typo3-flow-plugin': 'neos-plugin'
      'typo3-flow-build': 'neos-build'
      'typo3-flow-boilerplate': 'neos-boilerplate'
      'typo3-flow-site': 'neos-site'
      'typo3-flow-package': 'neos-package'
      'typo3-flow-framework': 'neos-framework'
      'neos-plugin': 'neos-plugin'
      'neos-build': 'neos-build'
      'neos-boilerplate': 'neos-boilerplate'
      'neos-site': 'neos-site'
      'neos-package': 'neos-package'
      'neos-framework': 'neos-framework'

    repository:
      identifier: '9127231f-d1b8-440f-8ef7-b05f760178fb'

TYPO3:

  TypoScript:
    defaultContext:
      MarketPlaceSearch: 'Neos\MarketPlace\Eel\ElasticSearchQueryBuilder'

  TYPO3CR:

    Search:
      defaultContext:
        MarketIndexing: 'Neos\MarketPlace\Eel\IndexingHelper'

  Neos:
    typoScript:
      autoInclude:
        'Neos.MarketPlace': TRUE

    userInterface:
      translation:
        autoInclude:
          'Neos.MarketPlace': ['NodeTypes/*']
